# Generated by Django 2.0.4 on 2018-04-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=9)),
                ('curso', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
