# Generated by Django 2.0.4 on 2018-04-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='curso',
            field=models.CharField(default='Engenharia Ambiental e Sanitária', max_length=100),
        ),
    ]
