# Generated by Django 2.0.4 on 2018-04-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180421_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='curso',
        ),
        migrations.AddField(
            model_name='materiadata',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.StudentData'),
        ),
    ]
